[package]
name = "tiny-vsock"
version = "0.1.1"
edition = "2024"

[features]
std-io = []

[dependencies]
anyhow = "1.0.101"
nix = { version = "0.31.1", features = ["socket"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }

[dev-dependencies]
serial_test = "3.3.1"
